name: Linter

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run format:check
